#!/usr/bin/env node
// audit/render-svg.mjs — render data.json (generated by gen-data.mjs from
// features.mjs + @mdn/browser-compat-data) into caniuse-style support
// grids, one SVG per feature, into audit/svg/. BROWSER.AUDIT.md embeds them
// with <img> tags (GitHub sanitizes raw inline <svg> in markdown, but
// renders SVG files referenced by <img> fine).
//
// Accessibility: color is never the only carrier — every cell shows a
// status glyph (✓ supported, ! caveat, ◷ recent, ✗ none) beside the
// version, and the header palette is chosen to survive both GitHub light
// and dark themes (img-embedded SVGs cannot read prefers-color-scheme).
//
// Usage: node audit/render-svg.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DATA = JSON.parse(fs.readFileSync(path.join(HERE, 'data.json'), 'utf8'));
const OUT = path.join(HERE, 'svg');
fs.mkdirSync(OUT, { recursive: true });

const COLORS = { y: '#2a9d3f', n: '#c4432b', a: '#b07f0e', r: '#3572b0' };
const GLYPHS = { y: '✓', n: '✗', a: '!', r: '◷' };
const SUBLABEL = { y: '', n: 'no', a: 'caveat', r: 'recent' };

const CELL_W = 112;
const CELL_H = 46;
const HEADER_H = 30;

function esc(s) {
  return String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function featureSvg(f) {
  const w = CELL_W * f.cells.length;
  const h = HEADER_H + CELL_H;
  const alt = f.cells.map((c) => `${c.b} ${c.status === 'n' ? 'no' : c.since} (${SUBLABEL[c.status] || 'supported'})`).join(', ');
  const parts = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(`${f.name}: ${alt}`)}">`,
    `<style>text{font:600 12px -apple-system,'Segoe UI',sans-serif;fill:#fff}.hdr{font-weight:700}.sub{font-weight:400;font-size:10px;opacity:.85}</style>`,
  ];
  f.cells.forEach((c, i) => {
    const x = i * CELL_W;
    // Header: slate that reads on both GitHub themes.
    parts.push(`<rect x="${x}" y="0" width="${CELL_W - 2}" height="${HEADER_H - 2}" fill="#57606a"/>`);
    parts.push(`<text class="hdr" x="${x + (CELL_W - 2) / 2}" y="${HEADER_H / 2 + 4}" text-anchor="middle">${esc(c.b)}</text>`);
    parts.push(`<rect x="${x}" y="${HEADER_H}" width="${CELL_W - 2}" height="${CELL_H - 2}" fill="${COLORS[c.status]}"/>`);
    const version = c.status === 'n' ? 'no' : esc(String(c.since).length > 12 ? `${String(c.since).slice(0, 11)}…` : c.since);
    parts.push(`<text x="${x + (CELL_W - 2) / 2}" y="${HEADER_H + CELL_H / 2 - 3}" text-anchor="middle">${GLYPHS[c.status]} ${version}</text>`);
    if (SUBLABEL[c.status]) {
      parts.push(`<text class="sub" x="${x + (CELL_W - 2) / 2}" y="${HEADER_H + CELL_H / 2 + 13}" text-anchor="middle">${SUBLABEL[c.status]}</text>`);
    }
  });
  parts.push('</svg>');
  return parts.join('\n');
}

function legendSvg() {
  const entries = [
    ['y', '✓ supported (first full-support version from MDN BCD)'],
    ['a', '! supported with caveat / interop hazard — read the note'],
    ['r', '◷ recent — check fleet coverage before relying on it'],
    ['n', '✗ not supported'],
  ];
  const w = 660;
  const h = 26 * entries.length + 8;
  const parts = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="legend: check supported, exclamation caveat, clock recent, cross unsupported">`,
    `<style>text{font:400 13px -apple-system,'Segoe UI',sans-serif;fill:#8b949e}</style>`,
  ];
  entries.forEach(([k, label], i) => {
    const y = 4 + i * 26;
    parts.push(`<rect x="4" y="${y}" width="34" height="20" fill="${COLORS[k]}"/>`);
    parts.push(`<text x="48" y="${y + 15}">${esc(label)}</text>`);
  });
  parts.push('</svg>');
  return parts.join('\n');
}

for (const f of DATA.features) {
  fs.writeFileSync(path.join(OUT, `${f.id}.svg`), featureSvg(f));
}
fs.writeFileSync(path.join(OUT, 'legend.svg'), legendSvg());
console.log(`wrote ${DATA.features.length + 1} SVGs to ${path.relative(process.cwd(), OUT)} (BCD ${DATA.bcdVersion})`);
